### ISSUE TITLE
Does not work anymore with WebStorm 2021.3.3

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [smokeelow/intellij-sfcc#10]
Hello, thx for your awesome plugin!

I just upgraded to the latest Webstom Version and it stoped working:

<img width="797" alt="Screenshot 2022-03-23 at 16 50 26" src="https://user-images.githubusercontent.com/1157580/159740496-2f99e118-d2d3-4b1d-acfd-c5c974f3a61c.png">

<img width="432" alt="Screenshot 2022-03-23 at 16 51 22" src="https://user-images.githubusercontent.com/1157580/159740731-c86698d9-9a71-45e8-bb87-10b37b034edc.png">

I don't have the contact to the developer of the Properties module - maybe you have or you could drop the dependency, if possible?

Thx a lot!
Andreas

**Comment by smokeelow** [comment]
was fixed
