### ISSUE TITLE
Debugger doesn't see variables declared with 'let'

### ISSUE THREAD

**Issue by adriansetniewski** [smokeelow/intellij-sfcc#11]
When declaring variables with 'let' e.g.:
`let a = 'test';`
the debbuger doesn't see the variable.
Variables declared with 'var' are visible.

**Comment by smokeelow** [comment]
hello,

yes, this is limitation of SFCC Debugger API

**Comment by adriansetniewski** [comment]
Thanks, I will use vars for now then. BR! :)

**Comment by adriansetniewski** [comment]
Ok, closing then. BR :)
