### ISSUE TITLE
Problems with uploading builded js files

### ISSUE THREAD

**Issue by Palko-Astound** [smokeelow/intellij-sfcc#13]
Plugin doesn't upload builded js files after building but source files.

Upload log in PhpStorm with plugin
![зображення](https://user-images.githubusercontent.com/85938909/188933210-617452eb-a763-4d02-959b-b9ba5a7be839.png)

Upload log in VS Code with the same configs
![зображення](https://user-images.githubusercontent.com/85938909/188934191-3c0de342-556f-46ae-a8d4-81a96b601e2f.png)

**Comment by smokeelow** [comment]
hi, in Intellij SFCC 2022.3 it should be fixed
