### ISSUE TITLE
PHPStorm 2022.3.4 freeze after installation

### ISSUE THREAD

**Issue by syjust** [smokeelow/intellij-sfcc#17]
Hi there,
Your plugin seems very cool,
But when I install it on my PHPStorm 2022.3.4 and restart the IDE,
PHPStorm runs but without any IHM available.

![Capture d’écran 2022-12-22 à 13 06 33](https://user-images.githubusercontent.com/328522/209131111-9458e89a-f77e-4ba5-98ab-b4ac93c769fd.png)

When I launch PHPStorm from the terminal with `export CORESVG_VERBOSE=1`, the following result appears multiple times while the IDE is still in frozen state (no IHM available, just the icon app started)

```
C/c command was given the wrong number of points.
Unhandled operator '.'
Unhandled operator '7'
Unhandled operator '3'
Unhandled operator '8'
Unhandled operator '3'
Unhandled operator '-'
Unhandled operator '3'
Unhandled operator '1'
Unhandled operator '.'
Unhandled operator '5'
Unhandled operator '4'
Unhandled operator '3'
Unhandled operator '5'
Unhandled operator '7'
Unhandled operator '.'
Unhandled operator '4'
Unhandled operator '7'
Unhandled operator '0'
Unhandled operator '7'
Unhandled operator '-'
Unhandled operator '3'
Unhandled operator '3'
Unhandled operator '.'
Unhandled operator '2'
Unhandled operator '0'
Unhandled operator '3'
Unhandled operator '1'
Unhandled operator '5'
Unhandled operator '7'
Unhandled operator '.'
Unhandled operator '4'
Unhandled operator '7'
Unhandled operator '0'
Unhandled operator '7'
Unhandled operator '-'
Unhandled operator '3'
Unhandled operator '5'
Unhandled operator '.'
Unhandled operator '2'
Unhandled operator '5'
Unhandled operator '3'
Unhandled operator '9'
```

It seems coming from an issue with "JetBrains Properties" plugin usage because if I remove this plugin, PHPStorm is able to restart (but "SFCC B2C" doesn't work of course) and if I keep "JetBrains Properties" but remove "SFCC B2C", PHPStorm is also able to restart as well.

FYI:
I'm on MacOS BigSur 11.7
MacBook Pro 16" inch 2019
Intel Core i9 2.4 GHz
Ram: 64 Go DDR4
HD SSD with sufficient space

Java 1.8.0_341-b10

**Comment by smokeelow** [comment]
Hello,

Hm, this is first time i see such issue.
Could you disable plugins and  send IDE logs ?
<img width="377" alt="image" src="https://user-images.githubusercontent.com/1822237/209132293-bc34ea65-8822-49bd-ac6a-fc77cd5a0c99.png">

Also, as possible fix, try delete `.idea` folder in your project, invalidate caches
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1822237/209132654-6dd1273a-125b-46e1-8441-7c4b2414e0b0.png">

and re-install plugins

**Comment by smokeelow** [comment]
i'll try reproduce on my side

**Comment by smokeelow** [comment]
hm, works for me
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1822237/209133687-23ca75dc-8348-4279-b6e5-1e571ec0a46a.png">


Do you have this installed and enabled https://plugins.jetbrains.com/plugin/11590-salesforce-commerce-cloud-sfcc-studio ?

if so, it needs to be removed

**Comment by syjust** [comment]
I just deactivated this [concurrent plugin](https://plugins.jetbrains.com/plugin/11590-salesforce-commerce-cloud-sfcc-studio) and everything works fine.
Sorry for the conveninence, it was on my side.

Thx for the quick reply 🙏

**Comment by smokeelow** [comment]
nice, thanks.
