### ISSUE TITLE
Cartridge list not being saved for some projects

### ISSUE THREAD

**Issue by iparkhomenko-alpenite** [smokeelow/intellij-sfcc#21]
For some projects after adding cartridges, next time you open it, files are not uploaded and you have to select all the cartridges again.
Another similar issue occured for different projects, when some cartridges are saved but some are still popping up each project lauch with a request to add.

**Comment by smokeelow** [comment]
> For some projects after adding cartridges, next time you open it, files are not uploaded and you have to select all the cartridges again.

Need more details here (video, how you close project/IDE etc.)

> Another similar issue occured for different projects, when some cartridges are saved but some are still popping up each project lauch with a request to add.

If you have duplicated cartridges in different directories, it will show this popup, but you can also check `Do not show` at the bottom left of the that dialog window (video would be helpful)

**Comment by iparkhomenko-alpenite** [comment]
@smokeelow Maybe in this case (if the issue is duplicated cartridge name), a cartridge lookup directory selection feature can be added? 
I mean like built in Intellij scope feature. So you can specify a folder/folders to look for cartridges in. This way we can exclude duplication lookup.
And I am not sure here, but such a behaviour may be the consequence of using symlinks (scenario 1 described).

**Comment by smokeelow** [comment]
> @smokeelow Maybe in this case (if the issue is duplicated cartridge name), a cartridge lookup directory selection feature can be added?

Yes,  `exclude` options will be provided

> And I am not sure here, but such a behaviour may be the consequence of using symlinks (scenario 1 described).

so in first scenario you use symlinks?

**Comment by iparkhomenko-alpenite** [comment]
Correct, symlinks. And original cartridges are in a project structure in a different folders.

![image](https://user-images.githubusercontent.com/112380881/218433518-9128cc8f-e679-4691-bd16-ebb35eb176b5.png)

cartridges folder contains normal cartridges + symlinked cartridges.
Repo folder contains original cartridges that are linked to cartridges folder.

**Comment by smokeelow** [comment]
looks like i found the issue for the first case, will be fixed in upcoming `2023.1` release
