### ISSUE TITLE
Extension is causing webstorm to constantly check for updates

### ISSUE THREAD

**Issue by SimplyComplexable** [smokeelow/intellij-sfcc#23]
Since updating to the latest version of the extension in Webstorm, I am constantly getting Webstorm's plugin updates popup, to the point, it's actually preventing me from working. 
I can't completely confirm that this extension is the culprit, but it didn't start until immediately after installing this update. I also disabled this extension for a couple of days while I was working on other projects the issue completely stopped but started again after re-enabling the extension. Hoping you could do a pass-through for anything that could be causing that. 
I also created [an issue](https://youtrack.jetbrains.com/issue/WEB-59559/Webstorm-and-Plugin-Updates-popup-showing-over-and-over-again) with Jetbrains, but they seem to think it's an extension issue.

**Comment by smokeelow** [comment]
hi, yes, will be fixed in upcoming `2023.1`

**Comment by SimplyComplexable** [comment]
@smokeelow any update on this? It's very disruptive to my work. I've resorted to disabling the extension whenever possible to avoid the constant popups.

**Comment by SimplyComplexable** [comment]
@smokeelow can you please release a fix for this? It's making my IDE basically unusable while the extension is turned on. I'm going to have to start using an alternatives to this extension if it isn't fixed soon.
I'd be happy to help if it would be useful. I hope all is well.

**Comment by smokeelow** [comment]
hi @SimplyComplexable , new update `2023.1` of the plugin is under JetBrains review,  they should approve it tomorrow.

It should be fixed there but please let me know if you will have some issues so i can fix them quickly.

Sorry for such issues

**Comment by smokeelow** [comment]
@SimplyComplexable update is available now, please download and let me know how it works for you

**Comment by SimplyComplexable** [comment]
Awesome thank you!

**Comment by smokeelow** [comment]
@SimplyComplexable i’m sorry  but there are one not a cool bug
i’ll release another update on Monday to fix it
 the bug is - you will see notification in the bottom right about new version of the plugin each 10 seconds  😅 (it should be 1 notification per hour)
 i was in hurry and missed to switch from test properties to production
