### ISSUE TITLE
While making debugging I cannot navigate other scripts and files.

### ISSUE THREAD

**Issue by iddemirjs** [smokeelow/intellij-sfcc#30]
While making debugging I cannot navigate other scripts and files. When I click another script or file debugger reback to current running line. I just able to seeing current running script.

**Comment by smokeelow** [comment]
hi @iddemirjs , is it possible to record some video to show the issue?

**Comment by iddemirjs** [comment]
https://user-images.githubusercontent.com/28766071/233101031-05e306ed-9177-4b39-826c-d325910ec493.mp4

**Comment by smokeelow** [comment]
@iddemirjs thanks for the video, now it's clear what's happening
i'll try reproduce and fix it

**Comment by iddemirjs** [comment]
Hi @smokeelow is it possible, Would you do a hotfix for this problem?

**Comment by smokeelow** [comment]
Hi @iddemirjs , another customer reported same issue and provided error stack. I hope it will help me to fix this, because it's really hard to reproduce this issue

**Comment by smokeelow** [comment]
hi @iddemirjs looks like i found the issue, i'll do a bug fix release on 26-27 Jun

**Comment by iddemirjs** [comment]
Hi @smokeelow,
Did you release your fix?

**Comment by smokeelow** [comment]
hi @iddemirjs  sorry for the delay
please check new update, if you will face this issue again you can create a new ticket. Thanks!

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
asdasdsassssss, @jackjin321, @SickProdigy, @zabuzafr, @nonevx, @zzzz438, @apeny, @tbfito, @0x00031337, @gnanet, @maybestone1980, @gitthinkoo, @dream80, @Nalrang, @Cupmouse, @Timmo223, @a1147211355, @Leadspie, @zeng-yh, @chrisport, @dogankoc, @9cat, @whatisgravity, @doglex, @langhai8045, @perfaram, @liberpike, @binRick, @sameerkanda, @hirorylabo, @rodnandes, @paavalan, @fxfactorial, @bahelit, @Disneylanden, @trsxnn, @artifexor, @tonijpower, @mrkwenzel, @0x2a94b5, @Fe0fan, @zhaoxulong, @qiaoshun8888, @senthilmk, @fangjinyi, @Lonstari, @maikyguanaes, @sergiocabral, @vd-rd, @allenown

**Comment by risangpinto** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
