### ISSUE TITLE
Make the keymap for deploying code configurable

### ISSUE THREAD

**Issue by SimplyComplexable** [smokeelow/intellij-sfcc#33]
The deploy code command is mapped to `CMD + SHIFT + D` by this extension. I have this combination mapped to a different command and so the two are interferring. I tried to find this option in the keymap settings but it seems like that one isn't configurable. Could this be updated so that it is among the configurable key maps?

**Comment by smokeelow** [comment]
yeah, at this point it's not configurable, but i totally agreed that it must be configurable.
Will be fixed in upcoming `2023.2` release

**Comment by smokeelow** [comment]
Available in 2023.2 https://medium.com/@sergeybevzuk/intellij-sfcc-2023-2-release-page-designer-support-forms-autocompletions-ui-ux-improvements-1260bc1b6ae2#eccd
