### ISSUE TITLE
Unable to connect to SFCC staging instance with certificate

### ISSUE THREAD

**Issue by jonathansayag** [smokeelow/intellij-sfcc#5]
### Description

I'm trying to connect to SFCC staging instance using a certificate.

### Expected Result

Connection is successful

### Current Result

Here is my result with Intellij : 

![image](https://user-images.githubusercontent.com/7573827/84486230-65717a00-ac9d-11ea-93a7-3908ba096de3.png)

To check if it was coming from my configuration, i used Eclipse & it works.

**Comment by smokeelow** [comment]
Fixed in 2020.1.6.10.6
