### ISSUE TITLE
Autocompletion not working when extending any file from base

### ISSUE THREAD

**Issue by suaterken** [smokeelow/intellij-sfcc#7]
Hello,

Autocompletion cannot find function when we extend helper from the base cartridge so it looks only in the base helper.

i.e.
![image](https://user-images.githubusercontent.com/7967939/104216943-03e3da80-543b-11eb-9414-4ed76febeb2b.png)

![image](https://user-images.githubusercontent.com/7967939/104216959-08a88e80-543b-11eb-8046-2abcd18e0c54.png)

![image](https://user-images.githubusercontent.com/7967939/104216965-0ba37f00-543b-11eb-99c5-65423dbbd899.png)

let me know if you need more detail

Regards,
Suat

**Comment by smokeelow** [comment]
Hi Ahmet,

Thanks for reporting the issue. This is known issue and the dev is still in progress. 

Also in your case i see custom method `assign`, so i'm not sure how it will work even after fix.

Could you please provide code of `assign` method (if possible) so i can use it as test case.

**Comment by suaterken** [comment]
Thank you for the fast response,

I cannot also CTRL + LMB on assign.js file here is the usage

> const assign = require('modules/server/assign');

and the file 
assign.js

> 'use strict';
> module.exports = function () {
>     var result = {};
>     Array.prototype.forEach.call(arguments, function (argument) {
>         if (typeof argument === 'object') {
>             Object.keys(argument).forEach(function (key) {
>                 result[key] = argument[key];
>             });
>         }
>     });
>     return result;
> };
>

**Comment by smokeelow** [comment]
thanks, i'll check  `CTRL+LMB` bug as well.

Did you marked `modules` folder as `Modules Root` ?
![image](https://user-images.githubusercontent.com/1822237/104222834-85436900-544b-11eb-8dae-56d5708b3078.png)

**Comment by suaterken** [comment]
Indeed I didn't mark it as Global modules root. Thank you for the response

**Comment by Adodo** [comment]
It is not working on css files. Also it resolves to base node module if there is one.

![image](https://user-images.githubusercontent.com/5030019/126904381-ee4a6ef6-508f-4d54-bd1a-9273827fb4e3.png)

**Comment by smokeelow** [comment]
Hi @Adodo , it is not supposed to work with client side (yet)
